In [1]:
import numpy as np
import math
import scipy.special

In [2]:
matrix_1 = np.matrix([[0.9, 0.3, 0.4], [0.2, 0.8, 0.2], [0.1, 0.5, 0.6]])

In [3]:
input_1 = np.matrix([[0.9], [0.1], [0.8]])

In [4]:
# nicht so gut!
out_1 = np.dot(matrix_1, input_1)
print(out_1)

[[1.16]
 [0.42]
 [0.62]]


In [5]:
# Nur in Python 3.x
A = matrix_1 @ input_1
A

matrix([[1.16],
        [0.42],
        [0.62]])

In [6]:
# Standard
B = np.matmul(matrix_1, input_1)
B

matrix([[1.16],
        [0.42],
        [0.62]])

In [10]:
def sigmoid (x):
    return scipy.special.expit(x) #F(x) = 1/(1 + e^(-x)), expit kann auch Arrays annehmen.

In [11]:
input_2 =sigmoid(out_1)

In [12]:
input_2

matrix([[0.76133271],
        [0.60348325],
        [0.65021855]])

In [13]:
matrix_2 = np.matrix([[0.3, 0.7, 0.5], [0.6, 0.5, 0.2], [0.8, 0.1, 0.9]])

In [14]:
out_2 = np.dot(matrix_2, input_2)

print(out_2)

[[0.97594736]
 [0.88858496]
 [1.25461119]]


In [ ]:
output = sigmoid(out_2)
print(output)